### ISSUE TITLE
좌우 스크롤 무한 스크롤로 구현하기

### ISSUE THREAD

**Issue by jjjjjinseo** [comprehensive-design/style_scanner_frontend#25]
##  🖊️ Detail
IntersactionObserver로 무한스크롤 구현했습니다.

## ⭐ Issue
#4

**Comment by jjjjjinseo** [comment]
일단 홈에서 피드를 5개 불러오는 걸로 고정했다. 
하지만 피드를 계속 불러와야 하니까, 무한 스크롤로 구현해야 될 것 같고..(잘 안되는 중 ..) 노력해보겠다

**Comment by jjjjjinseo** [comment]
![스크린샷 2024-05-06 152542](https://github.com/comprehensive-design/style_scanner_frontend/assets/164891776/7163c6ec-eb5c-44d8-b7f8-1e944fa41006)

피드 사진 키울까요..? 충분한가요..?

**Comment by jjjjjinseo** [comment]
스크롤 바 너무 못생겨서 없애버렸는데, 모든 창에서 다 사라져 버린답니다..? 어떡할까요

**Comment by eunznidang** [comment]
님 그거 module.css로 하고있음요? 안해서 다 적용되는거 아님요?
